output = "infra/record"
pkgname = "record"

[psql]
  dbname = "sample_post_app"
  host = "localhost"
  port = 5432
  user = "postgres"
  pass = ""
  sslmode = "disable"
  blacklist = ["goose_db_version"]
