// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts.proto

package api_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type CreatePostsRequest struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostsRequest) Reset()         { *m = CreatePostsRequest{} }
func (m *CreatePostsRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostsRequest) ProtoMessage()    {}
func (*CreatePostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{1}
}

func (m *CreatePostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostsRequest.Unmarshal(m, b)
}
func (m *CreatePostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostsRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostsRequest.Merge(m, src)
}
func (m *CreatePostsRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostsRequest.Size(m)
}
func (m *CreatePostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostsRequest proto.InternalMessageInfo

func (m *CreatePostsRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type ListPostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRequest) Reset()         { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()    {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{2}
}

func (m *ListPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRequest.Unmarshal(m, b)
}
func (m *ListPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRequest.Marshal(b, m, deterministic)
}
func (m *ListPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRequest.Merge(m, src)
}
func (m *ListPostsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPostsRequest.Size(m)
}
func (m *ListPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRequest proto.InternalMessageInfo

type ListPostsResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsResponse) Reset()         { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()    {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b14bd1586479c33d, []int{3}
}

func (m *ListPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsResponse.Unmarshal(m, b)
}
func (m *ListPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsResponse.Marshal(b, m, deterministic)
}
func (m *ListPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsResponse.Merge(m, src)
}
func (m *ListPostsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostsResponse.Size(m)
}
func (m *ListPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsResponse proto.InternalMessageInfo

func (m *ListPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "com.github.sample_post_app.Post")
	proto.RegisterType((*CreatePostsRequest)(nil), "com.github.sample_post_app.CreatePostsRequest")
	proto.RegisterType((*ListPostsRequest)(nil), "com.github.sample_post_app.ListPostsRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "com.github.sample_post_app.ListPostsResponse")
}

func init() { proto.RegisterFile("posts.proto", fileDescriptor_b14bd1586479c33d) }

var fileDescriptor_b14bd1586479c33d = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x56, 0x42, 0x5b, 0xd1, 0xab, 0xa8, 0xe0, 0xd4, 0xa1, 0x8a, 0x18, 0x22, 0x4f, 0x1d, 0x5a,
	0x47, 0x2a, 0x88, 0x01, 0x36, 0xd8, 0x80, 0x01, 0x85, 0x8d, 0xa5, 0x72, 0x5b, 0xab, 0x58, 0x24,
	0xb1, 0x89, 0xaf, 0x08, 0x18, 0x79, 0x05, 0x1e, 0x8d, 0x57, 0xe0, 0x35, 0x90, 0x90, 0x9d, 0x08,
	0x2a, 0x10, 0xa5, 0xe3, 0xd9, 0xdf, 0xcf, 0x7d, 0xa7, 0x0f, 0x3a, 0x46, 0x5b, 0xb2, 0xdc, 0x94,
	0x9a, 0x34, 0x46, 0x33, 0x9d, 0xf3, 0x85, 0xa2, 0xdb, 0xe5, 0x94, 0x5b, 0x91, 0x9b, 0x4c, 0x4e,
	0xdc, 0xf7, 0x44, 0x18, 0x13, 0xed, 0x2f, 0xb4, 0x5e, 0x64, 0x32, 0x11, 0x46, 0x25, 0xa2, 0x28,
	0x34, 0x09, 0x52, 0xba, 0xa8, 0x99, 0x6c, 0x08, 0x8d, 0x2b, 0x6d, 0x09, 0xbb, 0x10, 0xaa, 0x79,
	0x3f, 0x88, 0x83, 0xc1, 0x4e, 0x1a, 0xaa, 0x39, 0xf6, 0xa0, 0x49, 0x8a, 0x32, 0xd9, 0x0f, 0xe3,
	0x60, 0xd0, 0x4e, 0xab, 0x81, 0x9d, 0x03, 0x9e, 0x95, 0x52, 0x90, 0x74, 0x1c, 0x9b, 0xca, 0xfb,
	0xa5, 0xb4, 0x84, 0x87, 0xd0, 0x70, 0x6e, 0x9e, 0xdd, 0x19, 0xc7, 0xfc, 0xef, 0x65, 0xb8, 0xe3,
	0xa5, 0x1e, 0xcd, 0x10, 0x76, 0x2f, 0x95, 0xa5, 0x55, 0x25, 0x76, 0x01, 0x7b, 0x2b, 0x6f, 0xd6,
	0xe8, 0xc2, 0x4a, 0x3c, 0x82, 0xa6, 0xcf, 0xda, 0x0f, 0xe2, 0xad, 0x8d, 0xf4, 0x2b, 0xf8, 0xf8,
	0x23, 0x80, 0x8e, 0x9b, 0xaf, 0x65, 0xf9, 0xa0, 0x66, 0x12, 0x09, 0xe0, 0x7b, 0x79, 0xe4, 0xeb,
	0x64, 0x7e, 0x87, 0x8c, 0xfe, 0xb5, 0x65, 0xbd, 0x97, 0xb7, 0xf7, 0xd7, 0xb0, 0xcb, 0x5a, 0x89,
	0xf7, 0x3f, 0xf6, 0x31, 0xf1, 0x11, 0xda, 0x5f, 0x91, 0x70, 0xb8, 0x4e, 0xe4, 0xe7, 0x35, 0xa2,
	0xd1, 0x86, 0xe8, 0xea, 0x4e, 0xac, 0xeb, 0xfd, 0xb7, 0xb1, 0xf6, 0x3f, 0xe5, 0x37, 0xc3, 0x9a,
	0x3b, 0xd3, 0x79, 0xf2, 0x74, 0x27, 0x72, 0xf9, 0x9c, 0x54, 0x32, 0x23, 0x87, 0x18, 0x09, 0x63,
	0x5c, 0x2b, 0x4e, 0x84, 0x51, 0x13, 0x33, 0x9d, 0xb6, 0x7c, 0x23, 0x0e, 0x3e, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x5d, 0xfb, 0xb7, 0x2a, 0x5a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostsRequest, opts ...grpc.CallOption) (*Post, error)
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostsRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/com.github.sample_post_app.PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, "/com.github.sample_post_app.PostService/ListPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	CreatePost(context.Context, *CreatePostsRequest) (*Post, error)
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *CreatePostsRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServiceServer) ListPosts(ctx context.Context, req *ListPostsRequest) (*ListPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPosts not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.sample_post_app.PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.sample_post_app.PostService/ListPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.sample_post_app.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _PostService_ListPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts.proto",
}
