// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts.proto

package api_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("posts.proto", fileDescriptor_b14bd1586479c33d) }

var fileDescriptor_b14bd1586479c33d = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x2c, 0xcc, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x87, 0xf1, 0xcd, 0xa1, 0xc5, 0xc5, 0xb1, 0xf8, 0x08, 0x36, 0x01, 0x1d, 0xdd, 0x7c, 0x02,
	0xc1, 0xcd, 0x25, 0x5c, 0x42, 0x88, 0x87, 0x4d, 0xee, 0x4f, 0x73, 0x0a, 0xfa, 0xf4, 0x12, 0xdb,
	0xf9, 0xe3, 0xfb, 0x75, 0x3d, 0xa4, 0x6a, 0x35, 0x98, 0x45, 0x65, 0x37, 0x04, 0xc9, 0x26, 0xb1,
	0x3e, 0x5e, 0xde, 0x54, 0xca, 0x98, 0xa2, 0x6b, 0xd9, 0x11, 0x30, 0xec, 0x93, 0x48, 0x9a, 0xa2,
	0x25, 0xb0, 0xa5, 0x52, 0x44, 0x49, 0x59, 0xca, 0x7a, 0x1e, 0xb7, 0x5d, 0x7f, 0x95, 0xaa, 0xb7,
	0x38, 0xbf, 0x39, 0xc4, 0x8b, 0xb9, 0x1f, 0x56, 0x26, 0x48, 0xb6, 0x9f, 0x27, 0xe5, 0xf8, 0xb5,
	0x8b, 0x38, 0x36, 0x71, 0x24, 0xa0, 0x49, 0x67, 0x02, 0x3b, 0x78, 0xbf, 0xf9, 0x2b, 0xa7, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x51, 0xad, 0xa6, 0x8e, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
}

type postServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostServiceClient(cc *grpc.ClientConn) PostServiceClient {
	return &postServiceClient{cc}
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.sample_post_app.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "posts.proto",
}
